### PR TITLE
Capstone project: Raytracer

### PR DESCRIPTION
**Pull request by projdysvit**
[README of the project](https://github.com/projdysvit/raytracer/blob/dev/README.md)

### CODE REVIEW

**Review by vadimb892 — APPROVED** [review]
Cool. You made raytracer on bare wgpu. I like your work.

**Review by FairlyBet — APPROVED** [review]

**Review by FairlyBet — COMMENTED** [review]
Looks cool. Nice 👍

**Review by TheBestTvarynka — APPROVED** [review]

**Review by master-of-zen — APPROVED** [review]
LGTM

**Review by Dagunov — APPROVED** [review]
Very cool, great work!

**Pull request merged**
